DROP TABLE IF EXISTS users;
CREATE TABLE users(
  id SERIAL PRIMARY KEY,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(100) NOT NULL,
  name VARCHAR(100),
  current_city VARCHAR(100),
  join_date DATE DEFAULT current_timestamp
);

DROP TABLE IF EXISTS posts;
CREATE TABLE posts(
  id SERIAL PRIMARY KEY,
  description LONGTEXT NOT NULL,
  city VARCHAR(100),
  title VARCHAR(100)
);

DROP TABLE IF EXISTS city;
CREATE TABLE city(
  id SERIAL PRIMARY KEY,
  city VARCHAR(100)
);
